DROP TABLE Warehouse CASCADE CONSTRAINTS purge;
DROP TABLE Warehouse_Section CASCADE CONSTRAINTS purge;
DROP TABLE Employee CASCADE CONSTRAINTS purge;
DROP TABLE Product CASCADE CONSTRAINTS purge;
DROP TABLE Product_Type CASCADE CONSTRAINTS purge;
DROP TABLE Type_Location CASCADE CONSTRAINTS purge;
DROP TABLE Stored_In CASCADE CONSTRAINTS purge;
DROP TABLE Prod_Belong_Type CASCADE CONSTRAINTS purge;
DROP TABLE Stock CASCADE CONSTRAINTS purge;
DROP TABLE Orders CASCADE CONSTRAINTS purge;--
DROP TABLE Order_Processing CASCADE CONSTRAINTS purge;
DROP TABLE Supplier CASCADE CONSTRAINTS purge;
DROP TABLE Incoming_Order CASCADE CONSTRAINTS purge;
DROP TABLE Distributor CASCADE CONSTRAINTS purge;
DROP TABLE Outgoing_Order CASCADE CONSTRAINTS purge;
DROP TABLE Order_Tracking CASCADE CONSTRAINTS purge;

DROP SEQUENCE wh_seq;
DROP SEQUENCE wh_sec_seq;
DROP SEQUENCE emp_seq;
DROP SEQUENCE prd_seq;
DROP SEQUENCE prd_type_seq;
DROP SEQUENCE stock_seq;
DROP SEQUENCE order_seq;
DROP SEQUENCE supp_seq;
DROP SEQUENCE dist_seq;
